### ISSUE TITLE
Proxying requests through another server causes VS to crash

### ISSUE THREAD

**Issue by ctolkien** [madskristensen/BrowserReloadOnSave#1]
- Visual Studio: 2015 Community
- This extension: version 1.0.11

We are using proxying requests through to IIS Express via https://github.com/webpack/webpack-dev-server. When we access a page that has been proxy'd through when this extension is active, VS crashes.

Best info I could dig up by attaching another copy of VS:

System.ArgumentNullException was unhandled
Message: An unhandled exception of type 'System.ArgumentNullException' occurred in mscorlib.dll
Additional information: Value cannot be null.

I'm not actually fussed about this extension working in this scenario (I imagine it's some limitation with proxying web socket requests), and webpack-dev-server is fulfilling this role, however would be good for VS to keep on trucking. 

At the moment, having to enable/disable this plugin depending on the particular project and the tools used.

**Comment by madskristensen** [comment]
Thanks for reporting this. What type of project are you using (ASP.NET Core/5, ASP.NET MVC 4/5, WebForms, or...?)

**Comment by ctolkien** [comment]
Hey Mads,

This is a regular MVC 5 site. Let me know if I can trial the above fix in a build somehow and I'll give it a whirl.

**Comment by madskristensen** [comment]
The latest CI build is here for testing http://vsixgallery.com/extension/2d8aa02a-8810-421f-97b9-86efc573fea3/

**Comment by ctolkien** [comment]
No dice, here's a better stack trace:

> System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>DefaultDomain</AppDomain><Exception><ExceptionType>System.ArgumentNullException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Value cannot be null.
> Parameter name: key</Message><StackTrace>   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>    at BrowserReloadOnSave.ReloadFactory.CreateExtensionInstance(BrowserLinkConnection connection) in C:\projects\browserreloadonsave\src\BrowserLink\ReloadFactory.cs:line 28
>    at Microsoft.VisualStudio.Web.BrowserLink.FactoryManager.CreateExtensionsForConnection(BrowserLinkConnection connection)
>    at Microsoft.VisualStudio.Web.BrowserLink.FactoryManager.PreConnected(Object sender, ConnectionEventArgs e)
>    at Microsoft.VisualStudio.Web.BrowserLink.ConnectionsImpl.FirePreConnected(BrowserLinkConnection connection)
>    at Microsoft.VisualStudio.Web.BrowserLink.ConnectionsImpl.AddConnection(BrowserLinkConnection connection)
>    at Microsoft.VisualStudio.Web.BrowserLink.SignalRSelfHost.ArteryConnection.&amp;lt;&amp;gt;c__DisplayClass8_0.&amp;lt;OnConnected&amp;gt;b__0()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)</StackTrace><ExceptionString>System.ArgumentNullException: Value cannot be null.
> Parameter name: key
>    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>    at BrowserReloadOnSave.ReloadFactory.CreateExtensionInstance(BrowserLinkConnection connection) in C:\projects\browserreloadonsave\src\BrowserLink\ReloadFactory.cs:line 28
>    at Microsoft.VisualStudio.Web.BrowserLink.FactoryManager.CreateExtensionsForConnection(BrowserLinkConnection connection)
>    at Microsoft.VisualStudio.Web.BrowserLink.FactoryManager.PreConnected(Object sender, ConnectionEventArgs e)
>    at Microsoft.VisualStudio.Web.BrowserLink.ConnectionsImpl.FirePreConnected(BrowserLinkConnection connection)
>    at Microsoft.VisualStudio.Web.BrowserLink.ConnectionsImpl.AddConnection(BrowserLinkConnection connection)
>    at Microsoft.VisualStudio.Web.BrowserLink.SignalRSelfHost.ArteryConnection.&amp;lt;&amp;gt;c__DisplayClass8_0.&amp;lt;OnConnected&amp;gt;b__0()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)</ExceptionString><DataItems><Data></Data></DataItems></Exception></TraceRecord>

**Comment by madskristensen** [comment]
Thanks, that's much better. I can see what the issue is now and a fix is coming. It appears that when you're using the proxy, Browser Link can't find the project for the connection and that's what causes the issue. I have a fix coming in a few minutes.

**Comment by madskristensen** [comment]
The latest version is ready in a few minutes on the same URL as before. This won't make the extension work for your particular project, but it will prevent VS from crashing

**Comment by ctolkien** [comment]
That's fixed it!

> This won't make the extension work for your particular project, but it will prevent VS from crashing

Yep, as long as VS doesn't fall over, all good :+1:

**Comment by madskristensen** [comment]
Thanks so much for the stack trace. Very much appreciated!!
