### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [madskristensen/BrowserReloadOnSave#23]
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by ynsbldk** [comment]
its not working .. vs 2022

**Comment by andrew-quicklution** [comment]
Any plans to make it work for VS 2022?

**Comment by madskristensen** [comment]
This is built in to VS 2022 in the form of Hot Reload
