### ISSUE TITLE
Will this work with owin hosting?

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/BrowserReloadOnSave#3]
A lot of my projects use [NancyFX](https://github.com/NancyFx/Nancy) as owin middleware and the [SystemWeb host](https://www.nuget.org/packages/Microsoft.Owin.Host.SystemWeb/), will this work for those types of projects?

**Comment by madskristensen** [comment]
It works in any project where Browser Link works. If Browser Link is connected but this extension doesn't work, then it's a bug in this extension. Is that the case?

**Comment by xt0rted** [comment]
Browser Link has never worked for me when using owin hosting which is why I was wondering about this plugin. I'm not sure why it's never worked though.

**Comment by madskristensen** [comment]
It requires the ASP.NET pipeline from either System.Web (ASP.NET 4.x) or ASP.NET Core using the Browser Link middleware. It doesn't work for any other setups unfortunately. Please report it to the [ASP.NET Tooling](https://github.com/aspnet/tooling) issue tracker.
