### ISSUE TITLE
help!it is not work in my vs2015 

### ISSUE THREAD

**Issue by wonderfuer** [madskristensen/BrowserReloadOnSave#4]
not use for me.but it is work when i enter 'ctrl+alt+enter'.Browser Link panel shows that the connection is alive.
thanks for help me!
vs2015 enterprise update2 .i am using aspx file.

**Comment by madskristensen** [comment]
Just save the .aspx file (Ctrl+S). Does that refresh the browser?

**Comment by wonderfuer** [comment]
not ,it doesn`t.i am confused about that.what else suggestions for me?

**Comment by vgl** [comment]
CSHTML  file on save not causing browser refresh...
![image](https://cloud.githubusercontent.com/assets/3647524/19068949/52b65cb4-8a2d-11e6-89b4-42f9c183c26a.png)

**Comment by vgl** [comment]
Does browser link works correctly in VS2015? Because even with my fix, its not reloading page in browser.

**Comment by freerider7777** [comment]
Reload on save does not work... manual refresh with pushing the refresh button works ok!
(Design and Inspect do not work also btw)

**Comment by freerider7777** [comment]
After some more experiments - reload on save works ok after VS restart (first project works fine). But if I load another project and run it - it shows as "Unknown" in Browser Link Dashboard and no reload on save happens!

**Comment by freerider7777** [comment]
why closed? it's not working on subsequent projects...
