### ISSUE TITLE
Reload doesn't work if edited in VS.NET 2015

### ISSUE THREAD

**Issue by dotnetshadow** [madskristensen/BrowserReloadOnSave#5]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [Browser Reload on Save 1.0.17]

### Description
Editing a file in Visual Studio does not trigger a reload, but editing a file using notepad does

### Steps to recreate
1. Open index.cshtml in Visual Studio 2015 Update 3
2. Edited the page by adding some markup
3. NO browser reload
4. Opened notepad and edited the file and the reload worked

Note browserlink is working and refreshing via the reload button works, but the automatic save reload doesn't

### Current behavior
Currently the reload doesn't happen on browsers after editing a page

### Expected behavior
Reload should occur on browsers after editing a page

**Comment by sinand99** [comment]
I can confirm that the extension does NOT work as stated bydotnetshadow.  In this state, this extension is useless in VS2015

**Comment by madskristensen** [comment]
Is Browser Link connected to VS? You can test that by hitting Ctrl+Alt+Enter to test that the browser reloads

**Comment by sinand99** [comment]
Yes connected and reload option is enabled. Ctrl+Alt+Enter works but does not auto update when cshtml file is changed and saved.

**Comment by madskristensen** [comment]
What type of project do you see this issue in? WebForms, MVC, ASP.NET Core or...?

**Comment by sinand99** [comment]
Just a simple ASP.NET MVC 5 project. Core is not installed. Pure vanilla Update 3 installation on a fresh Windows 10 machine.

**Comment by Larswa** [comment]
I am also seeing this, as reported here: https://github.com/madskristensen/BrowserReloadOnSave/issues/6

**Comment by sinand99** [comment]
Why closed this issue without actually fixing it?

**Comment by harikrishnakada** [comment]
Make sure you are not starting the application with debugging. For compile on the fly to work, the app must be started without debugging. Press CTRL+f5
